task: abs
mode: test_text
text_src: '../raw_data/temp.raw_src'
text_tgt: '../raw_data/temp.raw_tgt'
test_from: '../models/model_step_148000.pt'
batch_size: 3000
test_batch_size: 500
bert_data_path: '../bert_data/bert_data_cnndm_final/cnndm'
log_file: '../logs/val_abs_bert_cnndm_test'
model_path: '../models'
sep_optim: true
use_interval: true
visible_gpus: '1'
max_pos: 512
max_length: 200
alpha: 0.95
min_length: 50
result_path: '../results/abs_bert_cnndm_test'
